# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 021d1f12947d3d72edf83c59275a1dd0c8ab087117587546803c6454527628ce6e8f19e73fce269eacf98769eeb3d26159b6ccfc34ccb7f38d7863b059abd8f0

test:
  secret_key_base: d08100863f5960a8e0c1ac6331121a869fee86c5920bd062856c6de2a0d05d68aede87ed7290199c2df46cbe652c76eeea78b6549d5a39f43fc45a59095d11bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
